return {
  FEAR = {
    MAX = 100,
    POSSESSION_START = 35,
    DECAY_DELAY = 4.0,
    DECAY_PER_SECOND = 6.0,

    COST = {
      DREAD_PRESENCE = 20,
      CURSE_WAVE = 25,
      PASS_THE_CURSE = 0
    },

    GAIN = {
      NORMAL_IMPACT = 10,
      STABILITY_BREAK = 15,
      CURSE_WAVE_HIT = 10,
      DREAD_EXPOSURE_MAX = 12
    }
  },

  STABILITY = {
    MAX = 8,
    PASSIVE_REGEN_DELAY = 4.0,
    PASSIVE_REGEN_INTERVAL = 1.75,
    BLOOD_BATH_HEAL = 1,
    FRACTURED_THRESHOLD = 2,
    STAGGER_DURATION = 2.0,
    RESOLVE_DURATION = 1.75
  },

  DREAD_PRESENCE = {
    DURATION = 5.0,
    RADIUS = 425,
    COOLDOWN = 10.5,

    SLOW_CAP = 0.15,
    SLOW_RAMP_DURATION = 2.25,
    DREAD_DECAY_PER_SECOND = 2.0,

    MEANINGFUL_EXPOSURE_DELAY = 0.5,
    THINK_INTERVAL = 0.10,
    FEAR_GRANT_INTERVAL = 0.50
  },

  CURSE_WAVE = {
    RANGE = 1200,
    WIDTH = 200,
    SPEED = 1500,
    COOLDOWN = 7.5,

    PATH_VISION_RADIUS = 150,
    PATH_VISION_DURATION = 2.0,

    REVEAL_DURATION = 2.0,
    DIRECT_REVEAL_RADIUS = 100,
    REVEAL_THINK_INTERVAL = 0.10,
    REVEAL_VISION_TICK = 0.25,

    PARTICLE =
        "particles/units/heroes/hero_vengeful/"
        .. "vengeful_wave_of_terror.vpcf"
  }
}
